data_ingestion:
  data_source: "data/data.csv"
  processed_data_dir: "data"
  train_file: "train.csv"
  test_file: "test.csv"

data_preprocessing:
  train_file_path: "data/train.csv"
  test_file_path: "data/test.csv"
  processed_data_dir: "data/processed_data"
  processed_train_file: "preprocessed_train.csv"
  processed_test_file: "preprocessed_test.csv"

data_training:
  processed_train_path: "data/processed_data/preprocessed_train.csv"
  processed_test_path: "data/processed_data/preprocessed_test.csv"
  model_dir: "models/"
  model_pkl_file: models/model.pkl
